# Generated by Django 4.2.20 on 2025-05-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={
                'ordering': ('-updated', '-created', 'id'),
                'permissions': (('add_articles', 'can add articles'),),
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
